CREATE TABLE FILETTATURA(
	METRICA CHAR(4),
	PASSO_GROSSO BOOLEAN DEFAULT TRUE,
	DIMENSIONE_PASSO DOUBLE,
	MISURA_PIATTI DOUBLE NOT NULL,
	ALTEZZA DOUBLE NOT NULL,
	PRIMARY KEY(METRICA,PASSO_GROSSO)
);

CREATE TABLE DADO(
	CODICE_HASH INT PRIMARY KEY,
	FILETTATURA CHAR(4) REFERENCES FILETTATURA(METRICA) NOT NULL,
	DENOMINAZIONE CHAR(50) NOT NULL,
	LUOGO_PRODUZIONE CHAR(50),
	DATA_PRODUZIONE DATE,
	PESO DOUBLE,
	PREZZO DOUBLE NOT NULL,
	NUMERO_PEZZI INT DEFAULT 0
);

CREATE TABLE IMPIEGATO(
	CODICE INT AUTO_INCREMENT PRIMARY KEY,
	NOME CHAR(20),
	COGNOME CHAR(20),
	DATA_NASCITA DATE,
	MANSIONE CHAR(20),
	STIPENDIO INT NOT NULL,
	MAX_VENDITE_ANN0 INT NOT NULL,
	DATA_ENTRATA DATE NOT NULL
);

CREATE TABLE UTENTE(
	USERNAME CHAR(20) PRIMARY KEY,
	HASH_PASSWORD CHAR(32),
	ADMIN BOOLEAN DEFAULT FALSE,
	IMPIEGATO INT REFERENCES IMPIEGATO(CODICE) NOT NULL
);

CREATE TABLE VENDITA(
	CODICE INT AUTO_INCREMENT PRIMARY KEY,
	UTENTE CHAR(20) REFERENCES UTENTE(USERNAME) NOT NULL,
	DADO INT REFERENCES DADO(CODICE_HASH) NOT NULL,
	DATA DATE NOT NULL,
	NUMERO_PEZZI INT NOT NULL
);


INSERT INTO FILETTATURA VALUES ('M3',TRUE, 0.5, 5.5, 3);
INSERT INTO FILETTATURA VALUES ('M4',TRUE, 0.7, 7, 4);
INSERT INTO FILETTATURA VALUES ('M5',TRUE, 0.8, 8, 5);
INSERT INTO FILETTATURA VALUES ('M6',TRUE, 1, 10, 6);
INSERT INTO FILETTATURA VALUES ('M7',TRUE, 1, 11, 7);
INSERT INTO FILETTATURA VALUES ('M8',TRUE, 1.25, 13, 8);
INSERT INTO FILETTATURA VALUES ('M8',FALSE, 1, 13, 8);
INSERT INTO FILETTATURA VALUES ('M10',TRUE, 1.5, 16.5, 10);
INSERT INTO FILETTATURA VALUES ('M10',FALSE, 1.25, 16.5, 10);
INSERT INTO FILETTATURA VALUES ('M12',TRUE, 1.75, 18.5, 12);
INSERT INTO FILETTATURA VALUES ('M12',FALSE, 1.25, 18.5, 12);
INSERT INTO FILETTATURA VALUES ('M14',TRUE, 2, 21.5, 14);
INSERT INTO FILETTATURA VALUES ('M14',FALSE, 1.5, 21.5, 14);
INSERT INTO FILETTATURA VALUES ('M16',TRUE, 2, 24, 16);
INSERT INTO FILETTATURA VALUES ('M16',FALSE, 1.5, 24, 16);
INSERT INTO FILETTATURA VALUES ('M18',TRUE, 2.5, 27, 18);
INSERT INTO FILETTATURA VALUES ('M18',FALSE, 1.5, 27, 18);
INSERT INTO FILETTATURA VALUES ('M20',TRUE, 2.5, 30, 20);
INSERT INTO FILETTATURA VALUES ('M20',FALSE, 1.5, 30, 20);
INSERT INTO FILETTATURA VALUES ('M22',TRUE, 2.5, 33, 22);
INSERT INTO FILETTATURA VALUES ('M22',FALSE, 1.5, 33, 22);
INSERT INTO FILETTATURA VALUES ('M24',TRUE, 3, 36, 24);
INSERT INTO FILETTATURA VALUES ('M24',FALSE, 2, 36, 24);
INSERT INTO FILETTATURA VALUES ('M27',TRUE, 3, 41, 27);
INSERT INTO FILETTATURA VALUES ('M27',FALSE, 2, 41, 27);
INSERT INTO FILETTATURA VALUES ('M30',TRUE, 3.5, 46, 30);
INSERT INTO FILETTATURA VALUES ('M30',FALSE, 2, 46, 30);
INSERT INTO FILETTATURA VALUES ('M33',TRUE, 3.5, 50, 33);
INSERT INTO FILETTATURA VALUES ('M33',FALSE, 2, 50, 33);
INSERT INTO FILETTATURA VALUES ('M36',TRUE, 4, 55, 36);
INSERT INTO FILETTATURA VALUES ('M36',FALSE, 3, 55, 36);
INSERT INTO FILETTATURA VALUES ('M39',TRUE, 4, 60, 39);
INSERT INTO FILETTATURA VALUES ('M39',FALSE, 3, 60, 39);
INSERT INTO FILETTATURA VALUES ('M42',TRUE, 4.5, 65, 42);
INSERT INTO FILETTATURA VALUES ('M42',FALSE, 3, 65, 42);
INSERT INTO FILETTATURA VALUES ('M45',TRUE, 4.5, 70, 45);
INSERT INTO FILETTATURA VALUES ('M45',FALSE, 3, 70, 45);
INSERT INTO FILETTATURA VALUES ('M48',TRUE, 5, 75, 48);
INSERT INTO FILETTATURA VALUES ('M48',FALSE, 3, 75, 48);
INSERT INTO FILETTATURA VALUES ('M52',TRUE, 5, 80, 52);
INSERT INTO FILETTATURA VALUES ('M52',FALSE, 3, 80, 52);
INSERT INTO FILETTATURA VALUES ('M56',TRUE, 5.5, 85, 56);
INSERT INTO FILETTATURA VALUES ('M56',FALSE, 4, 85, 56);
INSERT INTO FILETTATURA VALUES ('M60',TRUE, 5.5, 90, 60);
INSERT INTO FILETTATURA VALUES ('M60',FALSE, 4, 90, 60);
