CREATE TABLE FILETTATURA(
	CODICE INTEGER PRIMARY KEY AUTOINCREMENT,
	METRICA CHAR(3) NOT NULL,
	PASSO_GROSSO BOOLEAN DEFAULT TRUE,
	DIMENSIONE_PASSO DOUBLE NOT NULL,
	MISURA_PIATTI DOUBLE NOT NULL,
	ALTEZZA DOUBLE NOT NULL,
	UNIQUE(METRICA,PASSO_GROSSO)
);

CREATE TABLE DADO(
	CODICE_HASH TEXT PRIMARY KEY,
	FILETTATURA INT REFERENCES FILETTATURA(CODICE) NOT NULL,
	MATERIALE CHAR(20) NOT NULL,
	CATEGORIA CHAR(1) NOT NULL,
	RIVESTIMENTO CHAR(20) NOT NULL,
	DENOMINAZIONE CHAR(50) NOT NULL,
	LUOGO_PRODUZIONE CHAR(50) NOT NULL,
	DATA_PRODUZIONE TEXT NOT NULL,
	PESO DOUBLE NOT NULL,
	PREZZO DOUBLE NOT NULL,
	NUMERO_PEZZI INT DEFAULT 0,
	CHECK(MATERIALE IN('Acciaio_5','Acciaio_8','Acciaio_10','AcciaioInox_A2','AcciaioInox_A4','Ottone_OT58','Ottone_OT63')),
	CHECK(CATEGORIA IN('A','B','C')),
	CHECK(RIVESTIMENTO IN('Nessuno','Brunitura','Fosfatazione','Zinco_Nichel','Zincatura_a_caldo'))
);

CREATE TABLE IMPIEGATO(
	CODICE INTEGER PRIMARY KEY AUTOINCREMENT,
	NOME CHAR(20) NOT NULL,
	COGNOME CHAR(20) NOT NULL,
	DATA_NASCITA TEXT NOT NULL,
	MANSIONE CHAR(20) NOT NULL,
	STIPENDIO INT NOT NULL,
	MAX_VENDITE_ANNO INT NOT NULL,
	DATA_ENTRATA TEXT NOT NULL,
	UNIQUE(NOME,COGNOME,DATA_NASCITA)
);

CREATE TABLE UTENTE(
	USERNAME CHAR(20) PRIMARY KEY,
	HASH_PASSWORD TEXT NOT NULL,
	ADMIN BOOLEAN DEFAULT FALSE,
	IMPIEGATO INT REFERENCES IMPIEGATO(CODICE) NOT NULL
);

CREATE TABLE VENDITA(
	CODICE INTEGER PRIMARY KEY AUTOINCREMENT,
	UTENTE CHAR(20) REFERENCES UTENTE(USERNAME) NOT NULL,
	DADO TEXT REFERENCES DADO(CODICE_HASH) NOT NULL,
	DATA TEXT NOT NULL,
	NUMERO_PEZZI INT NOT NULL
);


INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M3',TRUE, 0.5, 5.5, 3);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M4',TRUE, 0.7, 7, 4);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M5',TRUE, 0.8, 8, 5);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M6',TRUE, 1, 10, 6);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M7',TRUE, 1, 11, 7);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M8',TRUE, 1.25, 13, 8);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M8',FALSE, 1, 13, 8);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M10',TRUE, 1.5, 16.5, 10);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M10',FALSE, 1.25, 16.5, 10);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M12',TRUE, 1.75, 18.5, 12);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M12',FALSE, 1.25, 18.5, 12);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M14',TRUE, 2, 21.5, 14);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M14',FALSE, 1.5, 21.5, 14);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M16',TRUE, 2, 24, 16);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M16',FALSE, 1.5, 24, 16);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M18',TRUE, 2.5, 27, 18);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M18',FALSE, 1.5, 27, 18);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M20',TRUE, 2.5, 30, 20);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M20',FALSE, 1.5, 30, 20);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M22',TRUE, 2.5, 33, 22);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M22',FALSE, 1.5, 33, 22);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M24',TRUE, 3, 36, 24);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M24',FALSE, 2, 36, 24);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M27',TRUE, 3, 41, 27);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M27',FALSE, 2, 41, 27);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M30',TRUE, 3.5, 46, 30);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M30',FALSE, 2, 46, 30);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M33',TRUE, 3.5, 50, 33);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M33',FALSE, 2, 50, 33);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M36',TRUE, 4, 55, 36);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M36',FALSE, 3, 55, 36);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M39',TRUE, 4, 60, 39);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M39',FALSE, 3, 60, 39);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M42',TRUE, 4.5, 65, 42);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M42',FALSE, 3, 65, 42);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M45',TRUE, 4.5, 70, 45);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M45',FALSE, 3, 70, 45);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M48',TRUE, 5, 75, 48);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M48',FALSE, 3, 75, 48);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M52',TRUE, 5, 80, 52);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M52',FALSE, 3, 80, 52);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M56',TRUE, 5.5, 85, 56);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M56',FALSE, 4, 85, 56);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M60',TRUE, 5.5, 90, 60);
INSERT INTO FILETTATURA(METRICA,PASSO_GROSSO,DIMENSIONE_PASSO,MISURA_PIATTI,ALTEZZA) VALUES ('M60',FALSE, 4, 90, 60);
